FROM php:7.4.16-fpm-alpine as builder
RUN apk add --no-cache openssl bash mysql-client nodejs npm
RUN docker-php-ext-install pdo pdo_mysql bcmath

WORKDIR /var/www
RUN rm -rf /var/www/html

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY . /var/www

RUN composer install && \
     php artisan config:cache && \
     chmod -R 777 storage

RUN ln -s public html

EXPOSE 9000
ENTRYPOINT [ "php-fpm" ]
