version: "3"

services:
  app:
    build: .
    container_name: micro-videos-app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db
      - redis

  nginx:
    build: ./.docker/nginx
    container_name: micro-videos-nginx
    entrypoint: dockerize -template /etc/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf nginx -g "daemon off;"
    restart: always
    tty: true
    ports:
      - "8000:80"
    environment:
      - PHPFPM_HOST=app
      - PHPFPM_PORT=9000
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:5.7
    command: --innodb_use_native_aio=0
    container_name: micro-videos-db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
      - ./.docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: micro-videos-redis
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
