version: "3"

services:
  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: micro-catalog-rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbitmqdata:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - micro-catalog

networks:
  micro-catalog:
    driver: bridge
