apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: img-app-deployment
          name: app
          command:
            ["/bin/sh", "-c", "ln -s /var/www /usr/share/nginx; php-fpm;"]
          ports:
            - containerPort: 3306
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          envFrom:
            - configMapRef:
                name: app-conf
          volumeMounts:
            - name: app-conf
              mountPath: /var/www/.env
              subPath: .env
      volumes:
        - name: app-conf
          configMap:
            name: app-conf
            items:
              - key: env
                path: .env
